### ISSUE TITLE
无法正常使用

### ISSUE THREAD

**Issue by AIUSRTMP** [oahuil7/campusAutoAuth#1]
首先非常感谢学长能够编写此脚本。
我在测试的时候直接运行此脚本无法登陆网络，请问还有更新计划吗？

**Comment by AIUSRTMP** [comment]
C:\Windows\system32>node D:\campusAutoAuth\index.js
Error: write EPROTO 10590000:error:0A000172:SSL routines:tls12_check_peer_sigalg:wrong signature type:c:\ws\deps\openssl\openssl\ssl\t1_lib.c:1572:

**Comment by oahuil7** [comment]
同学你好，感谢star。因为我毕业了没办法测试，你可以参考一下学校bbs里其他人的解决方案：https://ecnu.im/d/438

**Comment by AIUSRTMP** [comment]
好的感谢~
